name: Version Checks

on:
  push:

jobs:
  validate:
    name: Validate VERSION File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: pip install packaging

      - name: Run version validation script
        run: |
          python3 scripts/reltool.py validate-version "${{ github.ref_type }}" "${{ github.ref_name }}"
